name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y curl make \
           curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh \
           ghcup install ghc 8.10.2 \
           ghcup set ghc 8.10.2 \
           ghcup install cabal 3.2.0.0 \
           cabal update
    - name: Run unit tests
      run: make test-chapter1 \
           make test-chapter2 \
           make test-chapter3 \
           make test-chapter4
